apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-canary
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iliefa/argocd-rollout
    targetRevision: HEAD
    path: examples/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}