apiVersion: v1
kind: Service
metadata:
  name: rollout-canary
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
    nodePort: 31124
  selector:
    app: rollout-canary